#!/usr/bin/env bash

# e: Exit at first error
# u: Treat undefined variables as errors
set -eu

# Get the directory of the current script
SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# Directory containing Dockerfiles, relative to the script directory
CONTAINERFILES_DIR="$SCRIPT_DIR/../containerfiles"

function main() {
    podman build \
        -f "$CONTAINERFILES_DIR/fedora_41.Containerfile" \
        -t "typewriter_fedora_41" \
        .

    podman run -it --rm "typewriter_fedora_41:latest"
}

main "$@"
