#!/usr/bin/env bash

# e: Exit at first error
# u: Treat undefined variables as errors
set -eu

# Get the directory of the current script
SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# Typewriter directory relative to the script directory
TYPEWRITER_DIR="$SCRIPT_DIR/../../"

function main() {
    podman build \
        -f "$SCRIPT_DIR/fedora_41.Containerfile" \
        -t "typewriter_fedora_41" \
        "$TYPEWRITER_DIR"

    podman run -it --rm \
        --volume "$TYPEWRITER_DIR":/root/.config/nvim:z \
        "typewriter_fedora_41:latest"
}

main "$@"
